version: '0.3.3-alpha-{build}'

platform:
- x64

cache:
- node_modules
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'

init:
- git config --global core.autocrlf input

install:
- ps: Install-Product node 6 x64
- set CI=true
- npm install -g npm@latest
- npm install

matrix:
  fast_finish: true

shallow_clone: true

clone_depth: 1

build_script:
- node --version
- npm --version
- npm run lint
- npm run test
- npm run dist-win

test: off

artifacts:
- path: dist\win\*
  name: npmkitwin

#deploy:
#  tag: npmkit-v0.3.2-alpha-build$(appveyor_build_version)
#  release: v0.3.2-alpha
#  description: ''
#  provider: GitHub
#  draft: true
#  force_update: true
#  artifact: npmkitwin
#  auth_token:
#    secure: iKOdJsnlkf8k7A/HVc5ssbphSKDIhXNKa5WugDkqyOuCAsQg7YZS7d9LPJJE55U0
