matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: node_js
      node_js: 9
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
before_install:
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn --ignore-engines
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn build
  - yarn test
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - yarn release
after_failure:
  - yarn create-diff-report
