matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: node_js
      node_js: 10
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
script:
  - yarn release
after_failure:
  - yarn create-diff-report
