language: node_js
node_js:
  - 8
os:
  - osx
osx_image: xcode9.2
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds
before_install:
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn lint
  - yarn build
  - yarn test
after_script:
  - greenkeeper-lockfile-upload
# after_success:
  # - yarn release
after_failure:
  - yarn create-diff-report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"