language: node_js
node_js:
  - 8
os:
  - osx
before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds
before_install:
  - yarn global add greenkeeper-lockfile@1
install:
  - yarn
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn run lint
  - yarn run pack
  - yarn run test
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - [[ $TRAVIS_BRANCH == "master" ]] && yarn release --mac --win --linux
after_failure:
  - yarn run create-diff-report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"