export const PROJECTS_LOAD = 'PROJECTS_LOAD';
export const PROJECTS_FILTER_SET = 'PROJECTS_FILTER_SET';
export const PROJECTS_FILTER_CLEAR = 'PROJECTS_FILTER_CLEAR';
export const PROJECT_OPEN = 'PROJECT_OPEN';
export const PROJECT_SET_ACTIVE = 'PROJECT_SET_ACTIVE';
export const PROJECT_REGISTER = 'PROJECT_REGISTER';
export const PROJECT_UNREGISTER = 'PROJECT_UNREGISTER';
export const PROJECT_STAR = 'PROJECT_STAR';
export const PROJECT_UNSTAR = 'PROJECT_UNSTAR';
export const PROJECT_DATA_UPDATE = 'PROJECT_DATA_UPDATE';

export const NOTIFICATION_SEND = 'NOTIFICATION_SEND';

export const NETWORK_STATUS_CHANGE = 'NETWORK_STATUS_CHANGE';

export const SCRIPTS_LOAD = 'SCRIPTS_LOAD';
export const SCRIPT_REGISTER = 'SCRIPT_REGISTER';
export const SCRIPT_UNREGISTER = 'SCRIPT_UNREGISTER';
export const SCRIPT_START = 'SCRIPT_START';
export const SCRIPT_RECEIVE_CHUNK = 'SCRIPT_RECEIVE_CHUNK';
export const SCRIPT_TOGGLE_OUTPUT = 'SCRIPT_TOGGLE_OUTPUT';
export const SCRIPT_FINISH = 'SCRIPT_FINISH';

export const DEPENDENCIES_LOAD = 'DEPENDENCIES_LOAD';
export const DEPENDENCY_REGISTER = 'DEPENDENCY_REGISTER';
export const DEPENDENCY_UNREGISTER = 'DEPENDENCY_UNREGISTER';
export const DEPENDENCY_CURRENT_VERSIONS_RECEIVE = 'DEPENDENCY_CURRENT_VERSIONS_RECEIVE';
export const DEPENDENCY_LATEST_VERSION_RECEIVE = 'DEPENDENCY_LATEST_VERSION_RECEIVE';
export const DEPENDENCY_LATEST_VERSIONS_RECEIVE = 'DEPENDENCY_LATEST_VERSIONS_RECEIVE';
export const DEPENDENCIES_INSTALLED_VERSION_REQUEST = 'DEPENDENCIES_INSTALLED_VERSION_REQUEST';
export const DEPENDENCIES_LATEST_VERSION_REQUEST = 'DEPENDENCIES_LATEST_VERSION_REQUEST';
export const DEPENDENCY_INSTALL_START = 'DEPENDENCY_INSTALL_START';
export const DEPENDENCY_INSTALL_FINISH = 'DEPENDENCY_INSTALL_FINISH';
export const DEPENDENCY_UNINSTALL_START = 'DEPENDENCY_UNINSTALL_START';
export const DEPENDENCY_UNINSTALL_FINISH = 'DEPENDENCY_UNINSTALL_FINISH';
export const DEPENDENCY_SET_WANTED_VERSION = 'DEPENDENCY_SET_WANTED_VERSION';
export const DEPENDENCY_VIEW_PAGE = 'DEPENDENCY_VIEW_PAGE';

export const META_CHECK = 'META_CHECK';
export const META_DIRECTORY_CREATE = 'META_DIRECTORY_CREATE';
export const META_DIRECTORY_REMOVE = 'META_DIRECTORY_REMOVE';
export const META_FILE_WRITE = 'META_FILE_WRITE';
export const META_FILE_WRITE_SUCCESS = 'META_FILE_WRITE_SUCCESS';
export const META_FILE_WRITE_ERROR = 'META_FILE_WRITE_ERROR';
export const META_FILE_READ = 'META_FILE_READ';

export const NODE_VERSION_REQUEST = 'NODE_VERSION_REQUEST';
export const NODE_VERSION_RECEIVE = 'NODE_VERSION_RECEIVE';

export const NPM_VERSION_REQUEST = 'NPM_VERSION_REQUEST';
export const NPM_VERSION_RECEIVE = 'NPM_VERSION_RECEIVE';
export const NPM_VERSION_FAILURE = 'NPM_VERSION_FAILURE';
export const NPM_COMMAND_START = 'NPM_COMMAND_START';
export const NPM_COMMAND_FINISH = 'NPM_COMMAND_FINISH';

export const CLIPBOARD_WRITE = 'CLIPBOARD_WRITE';

export const MODULE_EXPLORER_REQUEST = 'MODULE_EXPLORER_REQUEST';
export const MODULE_EXPLORER_RECEIVE = 'MODULE_EXPLORER_RECEIVE';
export const MODULE_EXPLORER_DETAILS = 'MODULE_EXPLORER_DETAILS';
export const MODULE_EXPLORER_RESET = 'MODULE_EXPLORER_RESET';

export const PROJECT_PICKER_SET_PACKAGES = '@picker/SET_PACKAGES';
export const PROJECT_PICKER_SET_PROJECT = '@picker/SET_PROJECT';
export const PROJECT_PICKER_SET_CATEGORY = '@picker/SET_CATEGORY';
