import cp from 'child_process';
import util from 'util';
import { join, resolve } from 'path';
import { ensureDir, writeJson } from 'fs-extra';
import preferences from '~/preferences';
import getPluginsDir from './base';

const execFileAsync = util.promisify(cp.execFile);
const yarn = resolve(__dirname, '../../bin/yarn-standalone.js');

async function install(pluginName) {
  const pluginsDir = getPluginsDir();
  const cacheDir = join(pluginsDir, 'cache');
  await ensureDir(pluginsDir);
  await ensureDir(cacheDir);
  await writeJson(join(pluginsDir, 'package.json'), {
    name: 'npmkit-plugins',
    description: 'Auto-generated by npmkit',
    private: true,
    version: '0.0.1',
    dependencies: preferences
      .get('plugins')
      .reduce((deps, name) => ({ ...deps, [name]: 'latest' }), {}),
  });
  await execFileAsync(
    process.execPath,
    [
      yarn,
      'install',
      '--no-emoji',
      '--no-lockfile',
      '--cache-folder',
      cacheDir,
    ],
    {
      cwd: pluginsDir,
      env: { NODE_ENV: 'production', ELECTRON_RUN_AS_NODE: 'true' },
      timeout: 1000 * 60 * 5,
      maxBuffer: 1024 * 1024,
    }
  );
  return __non_webpack_require__(getPluginsDir(pluginName));
}

export default install;
